name: Pull Request
description: Submit changes to the project
title: "[PR] "

body:
  - type: markdown
    attributes:
      value: |
        ## Pull Request
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the changes introduced by this pull request.
      placeholder: Describe the changes here...
    validations:
      required: true
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issue(s)
      description: Link to any related issues (e.g., `#123`) or explain if this addresses a specific feature, bug, documentation, or security issue.
      placeholder: List related issues here...
    validations:
      required: false
  - type: textarea
    id: changes-made
    attributes:
      label: Changes Made
      description: List the key changes made in this pull request.
      placeholder: |
        - Change 1
        - Change 2
        - Change 3
    validations:
      required: false
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Describe how you tested these changes.
      placeholder: |
        - [ ] Unit tests added/updated
        - [ ] Manual testing performed (describe below)
        - [ ] Other (please specify)

        **Testing Details**:
        Provide details about the testing environment, steps, or results.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or notes about the pull request here.
      placeholder: Add additional context, links, or drag and drop screenshots here...
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Confirm the following before submitting the pull request.
      options:
        - label: Code follows project style guidelines
          required: false
        - label: Tests pass locally
          required: false
        - label: Documentation updated (if applicable)
          required: false
        - label: Changes reviewed locally before submission
          required: false
