name: Documentation Issue
about: Report issues or suggest improvements for project documentation
title: '[Docs] '
labels: documentation
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue or improvement needed in the documentation.
      placeholder: Describe the documentation issue here...
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Specify where the issue exists (e.g., URL, file name, section title, or specific page in the documentation).
      placeholder: Provide the location of the issue...
    validations:
      required: false
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Describe the proposed correction or improvement to the documentation.
      placeholder: Describe the suggested fix here...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the documentation issue here.
      placeholder: Add additional context, links, or drag and drop screenshots here...
    validations:
      required: false
